### ISSUE TITLE
Error on packaging

### ISSUE THREAD

**Issue by Kas-2** [vatbub/matchmaking#24]
[INFO] matchmaking.parent *** FAILURE [12.318 s]

It says it is due to missing org.jetbrains.dokka:dokka-maven-plugin:0.10.0:javadoc: com/sun/tools/doclets/formats/html/HtmlDoclet

Do I have to compile WITHIN jetbrains?

**Comment by vatbub** [comment]
No, you don't, maven should work just fine. Would you mind posting the log output by maven?

**Comment by vatbub** [comment]
May I ask what you are working on? I made some heavy changes today, you therefore might want to pull again.

**Comment by Kas-2** [comment]
Hello vatbub, I am working on a game that needs Matchmaking, not sure if this is the correct project for that, but ok.

I will try to remember to send you the maven package error today!

**Comment by Kas-2** [comment]
https://pastebin.com/5PxHpcLr

**Comment by vatbub** [comment]
I just deployed the lib to my bintray repo where you can simply download it instead of having to build it 😎 

If you're using Maven:

```xml
<repositories>
	<repository>
		<snapshots>
			<enabled>false</enabled>
		</snapshots>
		<id>bintray-vatbub-fokprojectsReleases</id>
		<name>bintray</name>
		<url>https://dl.bintray.com/vatbub/fokprojectsReleases</url>
	</repository>
</repositories>
	
	<dependencies>
		<dependency>
			<groupId>com.github.vatbub</groupId>
			<artifactId>matchmaking.jvm-client</artifactId>
			<version>1.0-alpha-1</version>
		</dependency>
	</dependencies>
</repositories>
```

If you're using gradle:

```
repositories {
    maven {
        url  "https://dl.bintray.com/vatbub/fokprojectsReleases" 
    }
}

implementation 'com.github.vatbub:matchmaking.jvm-client:1.0-alpha-1'
```

You can download the server-war [here](https://bintray.com/vatbub/fokprojectsReleases/download_file?file_path=com%2Fgithub%2Fvatbub%2Fmatchmaking.server%2F1.0-alpha-1%2Fmatchmaking.server-1.0-alpha-1.war) and the standalone server launcher [here](https://bintray.com/vatbub/fokprojectsReleases/download_file?file_path=com%2Fgithub%2Fvatbub%2Fmatchmaking.standalone-server-launcher%2F1.0-alpha-1%2Fmatchmaking.standalone-server-launcher-1.0-alpha-1-jar-with-dependencies.jar).

PLease keep in mind that everything is in alpha stage, things might therefore not work as expected ;) Also, I would be glad to hear from you if you need help or have any kind of feedback 😎 Cheers :)

**Comment by Kas-2** [comment]
Hello vatbub, I will get back to this later this week!

**Comment by Kas-2** [comment]
Sorry for the inactivity, totally forgot this, can be closed, made something myself :)

Haven't fixed the issue described here tho
